# Use an official Python runtime as the base image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the backend code into the container
COPY . .

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expose the backend port
EXPOSE 8000

# Run the backend API
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "adminConfig.wsgi:application"]

